---
title: "Data Wrangling I Review - Tidy Data"
output: github_document
---

```{r setup}
library(tidyverse)
```


## `pivot_longer`

Load the PULSE data

```{r}
pulse_data = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names()
```

Instead of having four different columns for bdi scores, we have df with an ID including a column for visit baseline, 1 month, 6 month, 12 month

Wide format to long format ...

```{r}
pulse_data_tidy =
  pulse_data %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    names_prefix = "bdi_score_",
    values_to = "bdi"
  )
```
We cleaned the prefix here.

Rewrite, combine, and extend to add a mutate step
```{r}
pulse_data = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    names_prefix = "bdi_score_",
    values_to = "bdi"
  ) %>% 
    relocate(id, visit) %>% 
  mutate(visit = recode(visit, "bl" = "00m"))
```


## `pivot_wider`


Make up some data!

```{r}
analysis_result = 
  tibble(
    group = c("treatment", "treatment", "placebo", "placebo"),
    time = c("pre", "post", "pre", "post"),
    mean = c(4, 8, 3.5, 4)
  )

analysis_result %>% 
  pivot_wider(
    names_from = "time",
    values_from = "mean"
  )
```





